# MLflow local

version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.s4
    image: iris_mlops:latest
    container_name: iris-mlops
    # command: uvicorn app:app --host 0.0.0.0 --port 8000 --app-dir scripts/session_4
    command: sh -c "uvicorn app:app --reload"  # Correct the app location
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
      # Use local MLflow store (inside the container)
      MLFLOW_TRACKING_URI: file:/app/mlruns
    # volumes:
    #   # Mount local project folder to persist mlruns data
    #   - .:/app
    networks:
      - mlflow-net

networks:
  mlflow-net:
    driver: bridge
