version: "3.8"

networks:
  mlflow-net:
    driver: bridge

services:
  mlflow-db:
    image: postgres:14
    container_name: mlflow-db
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow_db
    volumes:
      - ./mlflow_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mlflow-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow"]
      interval: 5s
      retries: 10
      timeout: 3s

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - mlflow-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      retries: 20
      timeout: 5s

  create-bucket:
    image: minio/mc
    container_name: mlflow-create-bucket
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - mlflow-net
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb --ignore-existing myminio/mlflow-artifacts;
      mc policy set public myminio/mlflow-artifacts;
      "
    restart: "no"

  mlflow-server:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-server
    environment:
      MLFLOW_TRACKING_URI: http://mlflow-server:5000
      BACKEND_STORE_URI: postgresql://mlflow:mlflow@mlflow-db:5432/mlflow_db
      ARTIFACT_ROOT: s3://mlflow-artifacts/
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    ports:
      - "5000:5000"
    depends_on:
      mlflow-db:
        condition: service_healthy
      minio:
        condition: service_healthy
      create-bucket:
        condition: service_completed_successfully
    networks:
      - mlflow-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      retries: 30
      timeout: 5s

  web:
    build: .
    image: full_iris:latest
    container_name: iris-mlops
    command: uvicorn session_4.app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: 1
      MLFLOW_TRACKING_URI: http://mlflow-server:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    depends_on:
      mlflow-server:
        condition: service_healthy
    networks:
      - mlflow-net
