name: Fastapi Docker Image

# Trigger workflow
# on:
#   push:
#     branches:
#       - main  # This will run the workflow whenever there's a push to the 'main' branch

on:
  [workflow_dispatch]   # This enable run the workflow manually

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Log in to docker hub
      uses: docker/login-action@v2
      with:
          username: hoang12b48
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image using docker compose
      run: |
          docker compose -f docker-compose.yaml build

    - name: Tag docker image
      run: |
          docker tag fastapi_iris:latest hoang12b48/fastapi_iris:latest

    - name: Push docker image to docker hub
      run: |
          docker push hoang12b48/fastapi_iris:latest