name: Full Pipeline (Local MLflow)

on:
  [workflow_dispatch]  # Manual trigger

jobs:
  mlops-pipeline:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: file:/app/mlruns
      PYTHONUNBUFFERED: 1
      RUNNING_IN_DOCKER: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: hoang12b48
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker compose -f docker-compose-local.yaml build

      - name: Train model (local MLflow)
        run: |
          echo "Running training inside Docker..."
          docker compose -f docker-compose-local.yaml run --rm web python scripts/session_4/training.py

      - name: Test FastAPI health (optional)
        run: |
          docker compose -f docker-compose-local.yaml up -d web
          echo "Waiting for FastAPI..."
          sleep 5
          curl -f http://localhost:8000/health || (docker logs iris-mlops && exit 1)
          docker compose -f docker-compose-local.yaml down

      - name: Tag Docker image
        run: docker tag full_iris:latest hoang12b48/full_iris:latest

      - name: Push Docker image to Docker Hub
        run: docker push hoang12b48/full_iris:latest

      - name: Cleanup
        run: docker compose -f docker-compose-local.yaml down -v

      - name: Summary
        run: echo "Pipeline completed :Training → Test → Push"
